### ISSUE TITLE
Module won't build for kernel 6.11.*

### ISSUE THREAD

**Issue by mateuszdrab** [staralt/dxgkrnl-dkms#10]
Hello

Just wanted to bring it to your attention that the DKMS module for the new kernel `6.11.0-1012-azure` fails to compile. 
Worked fine on the 6.8 branch, so it must be something with the 6.11 branch.

Hope the below logs help. 
Could it be because the module is built from the 6.6 branch?

```
Building module:
Cleaning build area...
make -j2 KERNELRELEASE=6.11.0-1012-azure -C /lib/modules/6.11.0-1012-azure/build M=/var/lib/dkms/dxgkrnl/f6f9c9ab2/build...(bad exit status: 2)
ERROR (dkms apport): binary package for dxgkrnl: f6f9c9ab2 not found
Error! Bad return status for module build on kernel: 6.11.0-1012-azure (x86_64)
Consult /var/lib/dkms/dxgkrnl/f6f9c9ab2/build/make.log for more information.
```

```
DKMS make.log for dxgkrnl-f6f9c9ab2 for kernel 6.11.0-1012-azure (x86_64)
Sat Apr  5 18:22:03 BST 2025
make: Entering directory '/usr/src/linux-headers-6.11.0-1012-azure'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: x86_64-linux-gnu-gcc-13 (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0
  You are using:           gcc-13 (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0
  CC [M]  /var/lib/dkms/dxgkrnl/f6f9c9ab2/build/dxgmodule.o
  CC [M]  /var/lib/dkms/dxgkrnl/f6f9c9ab2/build/hmgr.o
/var/lib/dkms/dxgkrnl/f6f9c9ab2/build/hmgr.c: In function ???expand_table???:
/var/lib/dkms/dxgkrnl/f6f9c9ab2/build/hmgr.c:196:13: error: implicit declaration of function ???vzalloc???; did you mean ???kzalloc???? [-Werror=implicit-function-declaration]
  196 |             vzalloc(new_table_size * sizeof(struct hmgrentry));
      |             ^~~~~~~
      |             kzalloc
/var/lib/dkms/dxgkrnl/f6f9c9ab2/build/hmgr.c:195:21: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
  195 |         new_entry = (struct hmgrentry *)
      |                     ^
/var/lib/dkms/dxgkrnl/f6f9c9ab2/build/hmgr.c:205:17: error: implicit declaration of function ???vfree???; did you mean ???kvfree???? [-Werror=implicit-function-declaration]
  205 |                 vfree(table->entry_table);
      |                 ^~~~~
      |                 kvfree
/var/lib/dkms/dxgkrnl/f6f9c9ab2/build/dxgmodule.c: In function ???dxg_pci_probe_device???:
/var/lib/dkms/dxgkrnl/f6f9c9ab2/build/dxgmodule.c:615:43: warning: suggest braces around empty body in an ???if??? statement [-Wempty-body]
  615 |                 DXG_TRACE("err: %d",  ret);
      |                                           ^
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:244: /var/lib/dkms/dxgkrnl/f6f9c9ab2/build/hmgr.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [/usr/src/linux-headers-6.11.0-1012-azure/Makefile:1932: /var/lib/dkms/dxgkrnl/f6f9c9ab2/build] Error 2
make: *** [Makefile:224: __sub-make] Error 2
make: Leaving directory '/usr/src/linux-headers-6.11.0-1012-azure'
```

**Comment by staralt** [comment]
Thank you for your attention

You can use the updated install.sh from the 6.11 branch. Try the following command.

Please clean temporary files before running it.

```
curl -fsSL https://content.staralt.dev/dxgkrnl-dkms/6.11/install.sh | sudo bash -es 6.11.0-1012-azure
```

**Comment by mateuszdrab** [comment]
That does the trick, thank you for your efforts!
