### ISSUE TITLE
Failed to initialize NVML

### ISSUE THREAD

**Issue by johnlockejrr** [staralt/dxgkrnl-dkms#7]
The driver installed and loaded, distro rebooted. Any idea?
```
$ /usr/lib/wsl/lib/nvidia-smi
Failed to initialize NVML: GPU access blocked by the operating system
Failed to properly shut down NVML: GPU access blocked by the operating system
```
<img width="914" alt="Image" src="https://github.com/user-attachments/assets/89385aa5-4e25-493c-8120-eaf73a37b941" />

**Comment by johnlockejrr** [comment]
UPDATE: fixed it with these:

`https://github.com/mateuszdrab/hyperv-vm-provisioning/blob/master/Copy-HostGPUDriverToUbuntu.ps1`

and

`https://github.com/mateuszdrab/hyperv-vm-provisioning/blob/master/install-gpu.sh`

Seems not all the drivers files were copied from Windows.

**Comment by staralt** [comment]
> UPDATE: fixed it with these:
> 
> `https://github.com/mateuszdrab/hyperv-vm-provisioning/blob/master/Copy-HostGPUDriverToUbuntu.ps1`
> 
> and
> 
> `https://github.com/mateuszdrab/hyperv-vm-provisioning/blob/master/install-gpu.sh`
> 
> Seems not all the drivers files were copied from Windows.


Oh, Thank you. @johnlockejrr 

Perhaps, The D3D12 libraries, ```libd3d12core.so, etc.```, are no longer in ```C:\Windows\System32\lxss\lib```

I found the same issue

https://github.com/seflerZ/oneclick-gpu-pv/issues/8

and the below command in the above scripts you provided

```
scp -r "C:\Program Files\WSL\lib" ${UserName}@${TargetHost}:~/wsl/
```
```
ln -s /usr/lib/wsl/lib/libd3d12core.so /usr/lib/wsl/lib/libD3D12Core.so
ln -s /usr/lib/wsl/lib/libnvoptix.so.1 /usr/lib/wsl/lib/libnvoptix_loader.so.1
```

I will update the Prepare Step in the [README.md](https://git.staralt.dev/dxgkrnl-dkms/blob/main/README.md)

**Comment by staralt** [comment]
Can you try the new installation instructions and see if it works?

[README.md](https://github.com/staralt/dxgkrnl-dkms/blob/staralt/issue7/README.md)

**Comment by staralt** [comment]
If you've solved this issue, please feel free to open a pull request. I will handle your PR first.

**Comment by johnlockejrr** [comment]
I will make a new install on a new machine.

By the way, did you ever installed successfully on kernel 6.8, 6.9 or greater?
For me worked only on 6.1 or lower, on other I got compilation errors.
And any idea if I can suspend (not shutdown) the guest OS and resume with GPU on?

**Comment by johnlockejrr** [comment]
```
Building module:
Cleaning build area...
make -j12 KERNELRELEASE=6.12.12+bpo-amd64 -C /lib/modules/6.12.12+bpo-amd64/build M=/var/lib/dkms/dxgkrnl/be3283570/build...(bad exit status: 2)
Error! Bad return status for module build on kernel: 6.12.12+bpo-amd64 (x86_64)
Consult /var/lib/dkms/dxgkrnl/be3283570/build/make.log for more information.
Error! One or more modules failed to install during autoinstall.
Refer to previous errors for more information.
dkms: autoinstall for kernel: 6.12.12+bpo-amd64 failed!
run-parts: /etc/kernel/header_postinst.d/dkms exited with return code 11
Failed to process /etc/kernel/header_postinst.d at /var/lib/dpkg/info/linux-headers-6.12.12+bpo-amd64.postinst line 11.
dpkg: error processing package linux-headers-6.12.12+bpo-amd64 (--configure):
 installed linux-headers-6.12.12+bpo-amd64 package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 linux-headers-6.12.12+bpo-amd64
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

I'll try a 6.8 now, 6.12.12 doesn't seem to compile.

A lot of errors:

```
/var/lib/dkms/dxgkrnl/be3283570/build/dxgvmbus.c: In function ‘dxgvmb_send_reclaim_allocations’:
/var/lib/dkms/dxgkrnl/be3283570/build/dxgvmbus.c:3621:42: warning: suggest braces around empty body in an ‘if’ statement [-Wempty-body]
 3621 |                 DXG_TRACE("err: %d", ret);
      |                                          ^
/var/lib/dkms/dxgkrnl/be3283570/build/dxgvmbus.c: In function ‘dxgvmb_send_change_vidmem_reservation’:
/var/lib/dkms/dxgkrnl/be3283570/build/dxgvmbus.c:3651:42: warning: suggest braces around empty body in an ‘if’ statement [-Wempty-body]
 3651 |                 DXG_TRACE("err: %d", ret);
      |                                          ^
/var/lib/dkms/dxgkrnl/be3283570/build/dxgvmbus.c: In function ‘dxgvmb_send_destroy_hwqueue’:
/var/lib/dkms/dxgkrnl/be3283570/build/dxgvmbus.c:3815:42: warning: suggest braces around empty body in an ‘if’ statement [-Wempty-body]
 3815 |                 DXG_TRACE("err: %d", ret);
      |                                          ^
/var/lib/dkms/dxgkrnl/be3283570/build/dxgvmbus.c: In function ‘dxgvmb_send_query_adapter_info’:
/var/lib/dkms/dxgkrnl/be3283570/build/dxgvmbus.c:3899:42: warning: suggest braces around empty body in an ‘if’ statement [-Wempty-body]
 3899 |                 DXG_TRACE("err: %d", ret);
      |                                          ^
/var/lib/dkms/dxgkrnl/be3283570/build/dxgvmbus.c: In function ‘dxgvmb_send_submit_command_hwqueue’:
/var/lib/dkms/dxgkrnl/be3283570/build/dxgvmbus.c:3957:42: warning: suggest braces around empty body in an ‘if’ statement [-Wempty-body]
 3957 |                 DXG_TRACE("err: %d", ret);
      |                                          ^
/var/lib/dkms/dxgkrnl/be3283570/build/dxgvmbus.c: In function ‘dxgvmb_send_query_statistics’:
/var/lib/dkms/dxgkrnl/be3283570/build/dxgvmbus.c:3993:42: warning: suggest braces around empty body in an ‘if’ statement [-Wempty-body]
 3993 |                 DXG_TRACE("err: %d", ret);
      |                                          ^
cc1: some warnings being treated as errors
make[2]: *** [/usr/src/linux-headers-6.12.12+bpo-common/scripts/Makefile.build:234: /var/lib/dkms/dxgkrnl/be3283570/build/dxgvmbus.o] Error 1
make[2]: *** Waiting for unfinished jobs....
cc1: some warnings being treated as errors
make[2]: *** [/usr/src/linux-headers-6.12.12+bpo-common/scripts/Makefile.build:234: /var/lib/dkms/dxgkrnl/be3283570/build/hmgr.o] Error 1
cc1: some warnings being treated as errors
make[2]: *** [/usr/src/linux-headers-6.12.12+bpo-common/scripts/Makefile.build:234: /var/lib/dkms/dxgkrnl/be3283570/build/dxgadapter.o] Error 1
cc1: some warnings being treated as errors
make[2]: *** [/usr/src/linux-headers-6.12.12+bpo-common/scripts/Makefile.build:234: /var/lib/dkms/dxgkrnl/be3283570/build/ioctl.o] Error 1
make[1]: *** [/usr/src/linux-headers-6.12.12+bpo-common/Makefile:1962: /var/lib/dkms/dxgkrnl/be3283570/build] Error 2
make: *** [/usr/src/linux-headers-6.12.12+bpo-common/Makefile:236: __sub-make] Error 2
make: Leaving directory '/usr/src/linux-headers-6.12.12+bpo-amd64'
```

Compiled a 6.9.10 though

**Comment by johnlockejrr** [comment]
Need to test. A github user says that he successfully built the module on `6.12.9`.
`https://gist.github.com/Nislaco/c020c565fff05bef05a89647698073b1`

**Comment by johnlockejrr** [comment]
Confirmed:

<img width="1040" alt="Image" src="https://github.com/user-attachments/assets/01e6c028-c930-46e1-91a9-928493540e00" />

**Comment by staralt** [comment]
> ```    
> /var/lib/dkms/dxgkrnl/be3283570/build/dxgvmbus.c:3993:42: warning: suggest braces around empty body in an ‘if’ statement [-Wempty-body]
>  3993 |                 DXG_TRACE("err: %d", ret);
>       |                                          ^
> cc1: some warnings being treated as errors
> make[2]: *** [/usr/src/linux-headers-6.12.12+bpo-common/scripts/Makefile.build:234: /var/lib/dkms/dxgkrnl/be3283570/build/dxgvmbus.o] Error 1
> ```

```
cc1: some warnings being treated as errors
```

To ignore this, insert the ```-Wno-empty-body``` option into the compiler.

Here
install.sh:106:108
```
    # Patch a Makefile
    sed -i 's/\$(CONFIG_DXGKRNL)/m/' /usr/src/dxgkrnl-$VERSION/Makefile
    echo "EXTRA_CFLAGS=-I\$(PWD)/include -D_MAIN_KERNEL_" >> /usr/src/dxgkrnl-$VERSION/Makefile # !important
```

**Comment by johnlockejrr** [comment]
> > ```
> > /var/lib/dkms/dxgkrnl/be3283570/build/dxgvmbus.c:3993:42: warning: suggest braces around empty body in an ‘if’ statement [-Wempty-body]
> >  3993 |                 DXG_TRACE("err: %d", ret);
> >       |                                          ^
> > cc1: some warnings being treated as errors
> > make[2]: *** [/usr/src/linux-headers-6.12.12+bpo-common/scripts/Makefile.build:234: /var/lib/dkms/dxgkrnl/be3283570/build/dxgvmbus.o] Error 1
> > ```
> 
> ```
> cc1: some warnings being treated as errors
> ```
> 
> To ignore this, insert the `-Wno-empty-body` option into the compiler.
> 
> Here install.sh:106:108
> 
> ```
>     # Patch a Makefile
>     sed -i 's/\$(CONFIG_DXGKRNL)/m/' /usr/src/dxgkrnl-$VERSION/Makefile
>     echo "EXTRA_CFLAGS=-I\$(PWD)/include -D_MAIN_KERNEL_" >> /usr/src/dxgkrnl-$VERSION/Makefile # !important
> ```

You are right about this, here is my `Makefile` that worked on `6.12.9`:

```
# SPDX-License-Identifier: GPL-2.0
# Makefile for the hyper-v compute device driver (dxgkrnl).

obj-m   += dxgkrnl.o
dxgkrnl-y := dxgmodule.o hmgr.o misc.o dxgadapter.o ioctl.o dxgvmbus.o dxgprocess.o  dxgsyncfile.o
EXTRA_CFLAGS=-I$(PWD)/include -D_MAIN_KERNEL_ -DCONFIG_DXGKRNL=m -include /usr/src/dxgkrnl-be3283570test/include/extra-defines.h -I /usr/src/linux-source-6.12/include/linux/ -include /usr/src/linux-source-6.12/include/linux/vmalloc.h -Wno-empty-body
```

**Comment by johnlockejrr** [comment]
Any idea about this?
```
[    1.633239] dxgkrnl: loading out-of-tree module taints kernel.
[    1.633241] dxgkrnl: module verification failed: signature and/or required key missing - tainting kernel
[    1.634800] hv_vmbus: registering driver dxgkrnl
```
The module works but the kernel complains not being signed and tainting the kernel.

**Comment by staralt** [comment]
> Any idea about this?
> 
> ```
> [    1.633239] dxgkrnl: loading out-of-tree module taints kernel.
> [    1.633241] dxgkrnl: module verification failed: signature and/or required key missing - tainting kernel
> [    1.634800] hv_vmbus: registering driver dxgkrnl
> ```
> 
> The module works but the kernel complains not being signed and tainting the kernel.

You can ignore it. There is no problem.

Kernels with ```CONFIG_MODULE_SIG``` enabled and signed by official builders will complain about external vendor modules such as NVIDIA, AMD, Realtek, etc.

https://forums.developer.nvidia.com/t/pcie-tegra194-module-verification-failed-signature-and-or-required-key-missing-tainting-kernel/311108

**Comment by johnlockejrr** [comment]
Do you know any fix for black screen after `dxgkrnl` install? Other than disabling untill entering the GUI and enabling after?

```
× lightdm.service - Light Display Manager
     Loaded: loaded (/lib/systemd/system/lightdm.service; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Wed 2025-03-12 09:46:53 CET; 27min ago
   Duration: 9ms
       Docs: man:lightdm(1)
    Process: 1080 ExecStart=/usr/sbin/lightdm (code=exited, status=1/FAILURE)
   Main PID: 1080 (code=exited, status=1/FAILURE)
        CPU: 14ms

Mar 12 09:46:53 bunsenlabs systemd[1]: lightdm.service: Scheduled restart job, restart counter is at 5.
Mar 12 09:46:53 bunsenlabs systemd[1]: Stopped lightdm.service - Light Display Manager.
Mar 12 09:46:53 bunsenlabs systemd[1]: lightdm.service: Start request repeated too quickly.
Mar 12 09:46:53 bunsenlabs systemd[1]: lightdm.service: Failed with result 'exit-code'.
Mar 12 09:46:53 bunsenlabs systemd[1]: Failed to start lightdm.service - Light Display Manager.
Mar 12 09:46:53 bunsenlabs systemd[1]: lightdm.service: Triggering OnFailure= dependencies.
Mar 12 09:46:53 bunsenlabs systemd[1]: lightdm.service: Failed to enqueue OnFailure= job, ignoring: Unit plymouth-quit.service not found.
```

**Comment by staralt** [comment]
Sorry, I don't know. I'm not currently using a GUI system.

**Comment by johnlockejrr** [comment]
Ok. Just wanted to fix it. I don't normally use it, I use the GPU for ML.

**Comment by staralt** [comment]
I recently discovered the ```vgem``` kernel module for enabling hardware acceleration in WSL.

This might help you.

https://github.com/microsoft/WSL2-Linux-Kernel/tree/linux-msft-wsl-6.6.y/drivers/gpu/drm/vgem

**Comment by staralt** [comment]
> I recently discovered the `vgem` kernel module for enabling hardware acceleration in WSL.
> 
> This might help you.
> 
> https://github.com/microsoft/WSL2-Linux-Kernel/tree/linux-msft-wsl-6.6.y/drivers/gpu/drm/vgem


```
root@beta-build:~# ls /dev/dri
by-path  card0  card1  renderD128

root@beta-build:~# LIBVA_DRIVER_NAME=d3d12 vainfo --display drm --device /dev/dri/renderD128
Trying display: drm
libva info: VA-API version 1.20.0
libva info: User environment variable requested driver 'd3d12'
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/d3d12_drv_video.so
libva info: Found init function __vaDriverInit_1_20
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.20 (libva 2.18.0)
vainfo: Driver version: Mesa Gallium driver 24.0.9-0ubuntu0.3 for D3D12 (Intel(R) UHD Graphics 770)
vainfo: Supported profile and entrypoints
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSlice
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSlice
      VAProfileHEVCMain               : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointEncSlice
      VAProfileHEVCMain10             : VAEntrypointVLD
      VAProfileHEVCMain10             : VAEntrypointEncSlice
      VAProfileVP9Profile0            : VAEntrypointVLD
      VAProfileVP9Profile2            : VAEntrypointVLD
      VAProfileAV1Profile0            : VAEntrypointVLD
      VAProfileNone                   : VAEntrypointVideoProc
```

**Comment by johnlockejrr** [comment]
Just tested the install on `Ubuntu 22.04 LTS` and it works.

```
incognito@pop-os:~$ cat /etc/os-release
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
incognito@pop-os:~$ sudo lsmod | grep dx
dxgkrnl               208896  0
hv_vmbus              176128  10 hv_balloon,hv_utils,hv_netvsc,hid_hyperv,dxgkrnl,hv_storvsc,hyperv_keyboard,hyperv_drm,pci_hyperv,hyperv_fb
incognito@pop-os:~$ uname -a
Linux pop-os 6.12.10-76061203-generic #202412060638~1740154617~22.04~b4b3ebc SMP PREEMPT_DYNAMIC Fri F x86_64 x86_64 x86_64 GNU/Linux
incognito@pop-os:~$ nvidia-smi
Wed Mar 12 11:04:26 2025
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 570.86.16              Driver Version: 560.94         CUDA Version: 12.6     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4070        On  |   00000000:01:00.0  On |                  N/A |
|  0%  ERR!    P5             15W /  200W |    2003MiB /  12282MiB |      7%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+
```

Though I see this in `nvidia-smi`: `0%  ERR!    P5             16W /  200W` I don't know if I should be worried.

**Comment by staralt** [comment]
> Just tested the install on Ubuntu 22.04 LTS and it works.

Congratulations!

> Though I see this in nvidia-smi: 0%  ERR!    P5             16W /  200W I don't know if I should be worried.

Is it the same on the Windows host?

If the GPU works perfectly, you don't have to worry.

**Comment by johnlockejrr** [comment]
Yes is the same and it works, anyway I deleted the machine and installed a Server version becouse for my work the console is enough.

**Comment by staralt** [comment]
Oh, I see.

Thank you for your contribution :)
