### ISSUE TITLE
Error! Bad return status for module build on kernel: 5.15.167-0515167-generic (x86_64)

### ISSUE THREAD

**Issue by pursuecong** [staralt/dxgkrnl-dkms#5]
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package 'linux-image-5.15.0-119-generic' is not installed, so not removed
0 upgraded, 0 newly installed, 0 to remove and 74 not upgraded.
cfp@cfp:~$ sudo bash driver.sh
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
dkms is already the newest version (2.8.7-2ubuntu2.2).
git is already the newest version (1:2.34.1-1ubuntu1.12).
0 upgraded, 0 newly installed, 0 to remove and 74 not upgraded.
fatal: destination path 'WSL2-Linux-Kernel' already exists and is not an empty directory.
driver.sh: line 18: uapi/misc,linux}: No such file or directory
cp: cannot create regular file '/usr/src/dxgkrnl-6ac7abbd9/inc/uapi/misc/d3dkmthk.h': No such file or directory
cp: cannot create regular file '/usr/src/dxgkrnl-6ac7abbd9/inc/linux/hyperv_dxgkrnl.h': No such file or directory
Error! DKMS tree already contains: dxgkrnl-6ac7abbd9
You cannot add the same module/version combo more than once.

Kernel preparation unnecessary for this kernel. Skipping...

Building module:
cleaning build area...
make -j12 KERNELRELEASE=5.15.167-0515167-generic -C /lib/modules/5.15.167-0515167-generic/build M=/var/lib/dkms/dxgkrnl/6ac7abbd9/build...(bad exit status: 2)
ERROR (dkms apport): binary package for dxgkrnl: 6ac7abbd9 not found
Error! Bad return status for module build on kernel: 5.15.167-0515167-generic (x86_64)
Consult /var/lib/dkms/dxgkrnl/6ac7abbd9/build/make.log for more information.

Kernel preparation unnecessary for this kernel. Skipping...

Building module:
cleaning build area...
make -j12 KERNELRELEASE=5.15.167-0515167-generic -C /lib/modules/5.15.167-0515167-generic/build M=/var/lib/dkms/dxgkrnl/6ac7abbd9/build...(bad exit status: 2)
ERROR (dkms apport): binary package for dxgkrnl: 6ac7abbd9 not found
Error! Bad return status for module build on kernel: 5.15.167-0515167-generic (x86_64)
Consult /var/lib/dkms/dxgkrnl/6ac7abbd9/build/make.log for more information.

ubuntu uname -r 5.15.167-0515167-generic

make.log

/var/lib/dkms/dxgkrnl/6ac7abbd9/build/dxgkrnl.h:29:10: fatal error: uapi/misc/d3dkmthk.h: No such file or directory
   29 | #include <uapi/misc/d3dkmthk.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [scripts/Makefile.build:289: /var/lib/dkms/dxgkrnl/6ac7abbd9/build/hmgr.o] Error 1
In file included from /var/lib/dkms/dxgkrnl/6ac7abbd9/build/ioctl.c:21:
/var/lib/dkms/dxgkrnl/6ac7abbd9/build/dxgkrnl.h:29:10: fatal error: uapi/misc/d3dkmthk.h: No such file or directory
   29 | #include <uapi/misc/d3dkmthk.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [scripts/Makefile.build:289: /var/lib/dkms/dxgkrnl/6ac7abbd9/build/misc.o] Error 1
make[1]: *** [scripts/Makefile.build:289: /var/lib/dkms/dxgkrnl/6ac7abbd9/build/ioctl.o] Error 1
In file included from /var/lib/dkms/dxgkrnl/6ac7abbd9/build/dxgprocess.c:14:
/var/lib/dkms/dxgkrnl/6ac7abbd9/build/dxgkrnl.h:29:10: fatal error: uapi/misc/d3dkmthk.h: No such file or directory
   29 | #include <uapi/misc/d3dkmthk.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from /var/lib/dkms/dxgkrnl/6ac7abbd9/build/dxgvmbus.c:22:
/var/lib/dkms/dxgkrnl/6ac7abbd9/build/dxgkrnl.h:29:10: fatal error: uapi/misc/d3dkmthk.h: No such file or directory
   29 | #include <uapi/misc/d3dkmthk.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [scripts/Makefile.build:289: /var/lib/dkms/dxgkrnl/6ac7abbd9/build/dxgprocess.o] Error 1
In file included from /var/lib/dkms/dxgkrnl/6ac7abbd9/build/dxgsyncfile.c:34:
/var/lib/dkms/dxgkrnl/6ac7abbd9/build/dxgkrnl.h:29:10: fatal error: uapi/misc/d3dkmthk.h: No such file or directory
   29 | #include <uapi/misc/d3dkmthk.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [scripts/Makefile.build:289: /var/lib/dkms/dxgkrnl/6ac7abbd9/build/dxgvmbus.o] Error 1
make[1]: *** [scripts/Makefile.build:289: /var/lib/dkms/dxgkrnl/6ac7abbd9/build/dxgsyncfile.o] Error 1
In file included from /var/lib/dkms/dxgkrnl/6ac7abbd9/build/dxgadapter.c:19:
/var/lib/dkms/dxgkrnl/6ac7abbd9/build/dxgkrnl.h:29:10: fatal error: uapi/misc/d3dkmthk.h: No such file or directory
   29 | #include <uapi/misc/d3dkmthk.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [scripts/Makefile.build:289: /var/lib/dkms/dxgkrnl/6ac7abbd9/build/dxgadapter.o] Error 1
make: *** [Makefile:1912: /var/lib/dkms/dxgkrnl/6ac7abbd9/build] Error 2
make: Leaving directory '/usr/src/linux-headers-5.15.167-0515167-generic'

**Comment by pursuecong** [comment]
ubuntu2204

**Comment by timmeh87** [comment]
I had the same problem, and i read this issue which seemed related:

https://github.com/staralt/dxgkrnl-dkms/issues/4

I un-commented out the third patch ie, added it back in to the script, and then it worked.

**Comment by pursuecong** [comment]
Thank You

**Comment by pursuecong** [comment]
`In file included from /var/lib/dkms/dxgkrnl/6ac7abbd9/build/dxgprocess.c:14:
/var/lib/dkms/dxgkrnl/6ac7abbd9/build/dxgkrnl.h:746:41: error: field ‘gpadl’ has incomplete type
  746 |         struct vmbus_gpadl              gpadl;
      |                                         ^~~~~
In file included from /var/lib/dkms/dxgkrnl/6ac7abbd9/build/misc.c:18:
/var/lib/dkms/dxgkrnl/6ac7abbd9/build/dxgkrnl.h:746:41: error: field ‘gpadl’ has incomplete type
  746 |         struct vmbus_gpadl              gpadl;
      |                                         ^~~~~
In file included from /var/lib/dkms/dxgkrnl/6ac7abbd9/build/dxgadapter.c:19:
/var/lib/dkms/dxgkrnl/6ac7abbd9/build/dxgkrnl.h:746:41: error: field ‘gpadl’ has incomplete type
  746 |         struct vmbus_gpadl              gpadl;
      |                                         ^~~~~
In file included from /var/lib/dkms/dxgkrnl/6ac7abbd9/build/dxgmodule.c:18:
/var/lib/dkms/dxgkrnl/6ac7abbd9/build/dxgkrnl.h:746:41: error: field ‘gpadl’ has incomplete type
  746 |         struct vmbus_gpadl              gpadl;
      |                                         ^~~~~
In file included from /var/lib/dkms/dxgkrnl/6ac7abbd9/build/dxgvmbus.c:22:
/var/lib/dkms/dxgkrnl/6ac7abbd9/build/dxgkrnl.h:746:41: error: field ‘gpadl’ has incomplete type
  746 |         struct vmbus_gpadl              gpadl;
      |                                         ^~~~~
make[1]: *** [scripts/Makefile.build:289: /var/lib/dkms/dxgkrnl/6ac7abbd9/build/misc.o] Error 1
make[1]: *** Waiting for unfinished jobs....
In file included from /var/lib/dkms/dxgkrnl/6ac7abbd9/build/dxgsyncfile.c:34:
/var/lib/dkms/dxgkrnl/6ac7abbd9/build/dxgkrnl.h:746:41: error: field ‘gpadl’ has incomplete type
  746 |         struct vmbus_gpadl              gpadl;
      |                                         ^~~~~
make[1]: *** [scripts/Makefile.build:289: /var/lib/dkms/dxgkrnl/6ac7abbd9/build/hmgr.o] Error 1
make[1]: *** [scripts/Makefile.build:289: /var/lib/dkms/dxgkrnl/6ac7abbd9/build/dxgprocess.o] Error 1
In file included from /var/lib/dkms/dxgkrnl/6ac7abbd9/build/ioctl.c:21:
/var/lib/dkms/dxgkrnl/6ac7abbd9/build/dxgkrnl.h:746:41: error: field ‘gpadl’ has incomplete type
  746 |         struct vmbus_gpadl              gpadl;
      |                                         ^~~~~
make[1]: *** [scripts/Makefile.build:289: /var/lib/dkms/dxgkrnl/6ac7abbd9/build/dxgadapter.o] Error 1
make[1]: *** [scripts/Makefile.build:289: /var/lib/dkms/dxgkrnl/6ac7abbd9/build/dxgsyncfile.o] Error 1
make[1]: *** [scripts/Makefile.build:289: /var/lib/dkms/dxgkrnl/6ac7abbd9/build/dxgmodule.o] Error 1
make[1]: *** [scripts/Makefile.build:289: /var/lib/dkms/dxgkrnl/6ac7abbd9/build/dxgvmbus.o] Error 1
make[1]: *** [scripts/Makefile.build:289: /var/lib/dkms/dxgkrnl/6ac7abbd9/build/ioctl.o] Error 1
make: *** [Makefile:1912: /var/lib/dkms/dxgkrnl/6ac7abbd9/build] Error 2
`

**Comment by pursuecong** [comment]
I tried it but still have the problem. Is there something wrong with the Linux kernel?

**Comment by staralt** [comment]
> I had the same problem, and i read this issue which seemed related:
> 
> https://github.com/staralt/dxgkrnl-dkms/issues/4
> 
> I un-commented out the third patch ie, added it back in to the script, and then it worked.

Thank you. @timmeh87 

Patch #6 only worked on the Azure kernel probably because the sources came from the WSL kernel.

So, uncommenting the third patch solves the problem.

[Here](https://github.com/staralt/dxgkrnl-dkms/blob/staralt/issue5/install.sh) is the modified install.sh.

Before running the script, use the command below to clean up temporary data.

```bash
./install.sh clean all
```

**Comment by pursuecong** [comment]
I have used the updated install.sh, but the above-mentioned problem still exists.

**Comment by pursuecong** [comment]
```` C
DKMS make.log for dxgkrnl-6ac7abbd9 for kernel 5.15.167-0515167-generic (x86_64)
make: Entering directory '/usr/src/linux-headers-5.15.167-0515167-generic'
  CC [M]  /var/lib/dkms/dxgkrnl/6ac7abbd9/build/dxgmodule.o
  CC [M]  /var/lib/dkms/dxgkrnl/6ac7abbd9/build/hmgr.o
  CC [M]  /var/lib/dkms/dxgkrnl/6ac7abbd9/build/misc.o
  CC [M]  /var/lib/dkms/dxgkrnl/6ac7abbd9/build/dxgadapter.o
  CC [M]  /var/lib/dkms/dxgkrnl/6ac7abbd9/build/ioctl.ov
  CC [M]  /var/lib/dkms/dxgkrnl/6ac7abbd9/build/dxgvmbus.o
  CC [M]  /var/lib/dkms/dxgkrnl/6ac7abbd9/build/dxgprocess.o
  CC [M]  /var/lib/dkms/dxgkrnl/6ac7abbd9/build/dxgsyncfile.o
In file included from /var/lib/dkms/dxgkrnl/6ac7abbd9/build/dxgmodule.c:18:
/var/lib/dkms/dxgkrnl/6ac7abbd9/build/dxgkrnl.h:746:41: error: field ‘gpadl’ has incomplete type
  746 |         struct vmbus_gpadl              gpadl;
      |                                         ^~~~~
In file included from /var/lib/dkms/dxgkrnl/6ac7abbd9/build/dxgvmbus.c:22:
/var/lib/dkms/dxgkrnl/6ac7abbd9/build/dxgkrnl.h:746:41: error: field ‘gpadl’ has incomplete type
  746 |         struct vmbus_gpadl              gpadl;
      |                                         ^~~~~
In file included from /var/lib/dkms/dxgkrnl/6ac7abbd9/build/dxgadapter.c:19:
/var/lib/dkms/dxgkrnl/6ac7abbd9/build/dxgkrnl.h:746:41: error: field ‘gpadl’ has incomplete type
  746 |         struct vmbus_gpadl              gpadl;
      |                                         ^~~~~
In file included from /var/lib/dkms/dxgkrnl/6ac7abbd9/build/ioctl.c:21:
/var/lib/dkms/dxgkrnl/6ac7abbd9/build/dxgkrnl.h:746:41: error: field ‘gpadl’ has incomplete type
  746 |         struct vmbus_gpadl              gpadl;
      |                                         ^~~~~
In file included from /var/lib/dkms/dxgkrnl/6ac7abbd9/build/dxgsyncfile.c:34:
/var/lib/dkms/dxgkrnl/6ac7abbd9/build/dxgkrnl.h:746:41: error: field ‘gpadl’ has incomplete type
  746 |         struct vmbus_gpadl              gpadl;
      |                                         ^~~~~
In file included from /var/lib/dkms/dxgkrnl/6ac7abbd9/build/misc.c:18:
/var/lib/dkms/dxgkrnl/6ac7abbd9/build/dxgkrnl.h:746:41: error: field ‘gpadl’ has incomplete type
  746 |         struct vmbus_gpadl              gpadl;
      |                                         ^~~~~
In file included from /var/lib/dkms/dxgkrnl/6ac7abbd9/build/hmgr.c:19:
/var/lib/dkms/dxgkrnl/6ac7abbd9/build/dxgkrnl.h:746:41: error: field ‘gpadl’ has incomplete type
  746 |         struct vmbus_gpadl              gpadl;
      |                                         ^~~~~
In file included from /var/lib/dkms/dxgkrnl/6ac7abbd9/build/dxgprocess.c:14:
/var/lib/dkms/dxgkrnl/6ac7abbd9/build/dxgkrnl.h:746:41: error: field ‘gpadl’ has incomplete type
  746 |         struct vmbus_gpadl              gpadl;
      |                                         ^~~~~
make[1]: *** [scripts/Makefile.build:289: /var/lib/dkms/dxgkrnl/6ac7abbd9/build/misc.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [scripts/Makefile.build:289: /var/lib/dkms/dxgkrnl/6ac7abbd9/build/dxgprocess.o] Error 1
make[1]: *** [scripts/Makefile.build:289: /var/lib/dkms/dxgkrnl/6ac7abbd9/build/hmgr.o] Error 1
make[1]: *** [scripts/Makefile.build:289: /var/lib/dkms/dxgkrnl/6ac7abbd9/build/dxgsyncfile.o] Error 1
make[1]: *** [scripts/Makefile.build:289: /var/lib/dkms/dxgkrnl/6ac7abbd9/build/dxgmodule.o] Error 1
make[1]: *** [scripts/Makefile.build:289: /var/lib/dkms/dxgkrnl/6ac7abbd9/build/dxgadapter.o] Error 1
make[1]: *** [scripts/Makefile.build:289: /var/lib/dkms/dxgkrnl/6ac7abbd9/build/dxgvmbus.o] Error 
make[1]: *** [scripts/Makefile.build:289: /var/lib/dkms/dxgkrnl/6ac7abbd9/build/ioctl.o] Error 1
make: *** [Makefile:1912: /var/lib/dkms/dxgkrnl/6ac7abbd9/build] Error 2
````

**Comment by staralt** [comment]
Ahhh… Are the patches perfectly applied?
